### PR TITLE
Allow to specify r2d version via config on Image or Tale

### PR DESCRIPTION
**Pull request by Xarthisius**
This PR decouples *repo2docker_wholetale* version from *gwvolman* version. It comes handy in two cases:
1. when *r2d_wt* needs updates outside of normal WT release cycle,
1. when we're importing a Tale and want to use a specific version of r2d.
Note: the fallback preserves the current behavior of using r2d_wt image specified by `REPO2DOCKER_VERSION` constant which is still tied to tags (or == "latest" for `master`)

### How to test
1. Checkout this branch locally
1. Before deploying modify `setup_girder.py` in deploy-dev to create an additional RStudio Image (can be done later too if you prefer doing it manually)
    * handy shortcut: `curl -s http://use.yt/upload/d89070f6 | patch -p1`
1. Go to dashboard.
1. Create new Tales:
    1. with Image `RStudio`
    1. with Image `RStudio (R 4.0.2)`
1. Run both and confirm they run proper RStudio versions (see https://github.com/whole-tale/repo2docker_wholetale/pull/13 for details and image definition if you skipped 2.)

### CODE REVIEW

**Review by craig-willis — CHANGES_REQUESTED** [review]
This is great and the test scenario worked. As discussed, I do have reservations about setting the repo2docker_version on the image/environment. This is convenient for testing, but I don't think we want different images to have different values. For import also as discussed we could use the repo2docker_version stored in the manifest.

**Comment by Xarthisius** [comment]
> This is great and the test scenario worked. As discussed, I do have reservations about setting the repo2docker_version on the image/environment. This is convenient for testing, but I don't think we want different images to have different values. For import also as discussed we could use the repo2docker_version stored in the manifest.

Let me summarize the current state of things:
1. r2d version we're using is tied to a particular gwvolman commit running at any given time on our production deployment. E.g. as of time I'm writing it's gwvolman v0.9.1 and we have:
https://github.com/whole-tale/gwvolman/blob/4cc8f7fd9409bb3a0fb01dcdba6d4f3bec1e68a0/gwvolman/constants.py#L21
1. When a Tale is built and exported, information about r2d version is written to Tale's manifest.
1. We currently ignore that information during import, but we probably shouldn't.

In order to solve 3. I introduced the ability to set `repo2docker_version` as a part of `containerConfig` structure, which is a part of both Image and Tale model. Its primary functions are 1) for Image to provide reasonable defaults for building and executing containers 2) for Tale to be able to override the defaults. As of right now, per 1. all our images already have implicit `repo2docker_version` equal to the current release tag. It's just not visible. Yes, a side effect of this PR would enable us to set custom r2d version on individual images as defaults, but we **don't have to** do that.

**Review by craig-willis — APPROVED** [review]
OK, I'm good with these changes but it does raise some questions for the future about the r2d version.

With this PR, we have 4 different places where the r2d version is set.
1.  gwvolman constants: system default that changes with each release
2. `tale[imageInfo][repo2docker_version]`: set during build and used in `manifest.json` during export/publish.
3. `tale[config][repo2docker_version]`: introduced by this PR
4. `image[config][repo2docker_version]`: introduced by this PR

I understand that the `image[config][repo2docker_version]` is intended to support a specific case now and that the `tale[config][repo2docker_version]` could override this, but we don't have a way to set that value aside from API.

And this raises questions about future use cases:
* By default, any new tale uses the default version. New releases such as those that upgrade LTS version may cause users to want to pin to a given version or revert to an older version. How do we best handle this? (New UX discussion)
* A user imports a tale that was last built using an earlier version of r2d. In this case, the `tale[imageInfo][repo2docker_version]` stored in the `manifest.json` would become the `tale[config][repo2docker_version]` on import?  And again, the user may want to change this value to a newer version after import.

**Comment by Xarthisius** [comment]
Just a minor nitpick. This:

> 2\. tale[imageInfo][repo2docker_version]

is more of a record of what happened and cannot be used to set anything. The only scenario where it can play any role would be:

1. user creates and builds a vanilla Tale
1. we update the platform (changing default r2d)
1. user publish the Tale without rebuilding.

We should probably prevent that from happening.

**Comment by craig-willis** [comment]
So it won't be used on import to set `tale[config][repo2docker_version]`?  The `imageInfo[repo2docker_version]` is used to set the value of r2d used in the `run-local.sh` on export.

**Comment by Xarthisius** [comment]
> So it won't be used on import to set `tale[config][repo2docker_version]`? The `imageInfo[repo2docker_version]` is used to set the value of r2d used in the `run-local.sh` on export.

It will. I missed your question at the end. My bad.

**Review by ThomasThelen — APPROVED** [review]

**Pull request merged**
