### PR TITLE
Bug Fixes & Progress Updates for Publishing

### LINKED ISSUE #34: Package UUIDs should be prefixed
When a Tale is published to DataONE, we generate uuids to identify files/the package. We should be prefixing these uuids with `urn:uuid:`.

### PR DESCRIPTION
**Pull request by ThomasThelen**
This PR is a work in progress-but any feedback is appreciated. In retrospect I should have split this into two PRs.

### Set Custom Resource Map URL
I created `def createSimpleResourceMapCustom(ore_pid, scimeta_pid, sciobj_pid_list)` for the ability to add the URL to the ORE constructor (wasn't possible with `createSimpleResourceMap`). This was done to fix a bug where files weren't being properly located because the resource map was pointing to dataone production.

### Fix Access Rule
DataONE relies on the access rule to determine who can modify a published dataset. 
I fixed this at line 441 by adding the admin group. 

I noticed that the `sys_meta.submitter` wasn't being set, so I added it at line 422.

<br>
<br>

### Added the dev cn to `is_in_network` and `is_dev_url`:
These methods should have been checking against the development coordinating node.

###  Added `extract_user_name`
This method takes a JWT token and returns the full name inside.

### Added `get_resource_map_user`:
There's an issue where ORCIDs can't be https in the resource map. I created this method to make the ORCID HTTP.

### Added `generate_dataone_guid` to fix #34 
DataONE like to have `urn:uuid` attached to the front of GUIDs.

<br>
<br>

### Use DataONE GUID Format
Once change that you'll see throughout the file is the replacement of the uuid calls with `generate_dataone_guid`.

### Tale Yaml Format Changes
These can be ignored for now, and are subject to change as Craig and I flesh out the format. (LN 99-335)

### Raise Exceptions on Failure
There are a few places where I modified how errors are handled. Instead of hiding them, I let pass them up to gwvolman when we're unable to continue. (`create_upload_repository` is going to go away when we introduce repo2docker).

### create_upload_remote_file
I added a method that takes a remote HTTP file, downloads it, and then uploads it to DataONE.

### Send Job Status Updates

In the main publish method I added calls to `job_manager.updateProgress` so that the UI can do things like update progressbars and let the user know the current status. 
<br>
<br>

## Other Notes

The following functions are related to the serialization format and may be depreciated
1. `create_metadata_info_structure`
2. `create_environment_structure`
3. `create_outer_structure`
4. `create_upload_tale_yaml`

`create_upload_repository` will be depreciated with repo2docker; I put a DEVNOTE in for it.

### Hardcoded URL: #36 
Line 47 in gwvolman/dataone_metadata.py needs to be changed
Line 576 gwvolman/publish.py
- [x] Done

### Correct MB Conversion
Line 663 in gwvolman/publish.py needs to get cleaned up (and do a proper conversion)
- [x] Done

### Remove `logging.debug` statements
This commit should get squashed
- [x] Done

### Organize commits
- [x] Done

## Testing
This can be tested with the `dataone_publishing` branch on girder_wholetale.

1. Sign in to https://dev.nceas.ucsb.edu
2. Obtain your API key from account > my profile > Settings > Authentication Token
3. Navigate to your girder deployment and open the publish/dataone endpoint
4. Set `authToken` to the API key from above
5. Set `licenseSPDX` to `CC-BY-4.0`
6. Set `remoteMemberNode ` to `https://dev.nceas.ucsb.edu/knb/d1/mn`
7. Set `taleId` to the ID of any Tale
8. Set `itemIds` to a list of items ["item_id1", "item_id2", etc] that you want to publish
9. Click `Try it out!`
10. Navigate to `https://dev.nceas.ucsb.edu` and see that your Tale has been published

### CODE REVIEW

**Comment by craig-willis** [comment]
@ThomasThelen I've pushed a very heavy-handed refactor of the publishing implementation.  There are a few motivations:

1. Now that we have export, publish should just operate on the exported zip archive.  Any metadata (e.g., required by EML or resource map) must be present in the `manifest.json`.
1. We will be implementing several publish providers, so I've introduced the basic notion of the `PublishProvider` of which `DataONEPublishProvider` is the first one.
1. Moved all DataONE dependent code into `lib/dataone`. We are planning to refactor the tasks as well to split them up instead of piling stuff into tasks/utils/constants.

Specific modifications to your implementation:
* Moved almost everything into the `DataONEPublishProvider` and `DataONEMetadata` classes
* Changed to operate on the exported zip
* Modified Tale model to support an array of published packages (see https://github.com/whole-tale/girder_wholetale/pull/274). I tried to implement `obsoletes` but am hitting an error.
* Removed support for re-uploading of HTTP resources and linking with DataONE resources for now.  We can add these back in the future, but for v0.7 a published Tale should look just like an exported tale.
* In general, I tried to minimize the number of one- and two-line functions that are used in single place.

Please take a look -- I'm sure there are glaring omissions.

**Comment by ThomasThelen** [comment]
Looks great, I've addressed some of the comments below; I'm yet to test with the dataone_publishing dashboard branch.


Regarding [this](https://github.com/whole-tale/gwvolman/blob/33398680b35625a85166357744b9d2d8b2478f9f/gwvolman/lib/dataone/publish.py#L33). It's possible to keep a connection open between file transfers, but early on I found that every once and a while files would get dropped. I spoke with the d1_python author about it and he suggested I re-establish the connection for each file, which is what the `"Connection": "close"` header does. It's a bit slower, but more reliable.


Regarding [this](https://github.com/whole-tale/gwvolman/blob/33398680b35625a85166357744b9d2d8b2478f9f/gwvolman/lib/dataone/publish.py#L251). Objects in DataONE aren't really meant to be deleted (only admins can), so you won't be able to delete these. I confirmed this in the DataONE slack channel.


Regarding [this](https://github.com/whole-tale/gwvolman/blob/33398680b35625a85166357744b9d2d8b2478f9f/gwvolman/lib/dataone/publish.py#L287). Now that we're using the DataONE client to get pids, we shouldn't need this.

**Comment by ThomasThelen** [comment]
In [this package](https://dev.nceas.ucsb.edu/view/urn:uuid:e5a93957-2606-4fae-8871-53ea6d867e85) I noticed that the license text had the encoding included (see image)
Screen Shot 2019-03-22 at 10 21 32 AM

It stems from the EML, about 20 lines down
```
 <intellectualRights>
         <section>
            <para>
               <literalLayout>b'This work is licensed under the Creative Commons Attribution 4.0 International License. To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.'</literalLayout>
            </para>
         </section>
</intellectualRights>
```

**Comment by craig-willis** [comment]
@ThomasThelen as discussed, I think the license encoding problem was the last you thought needed to be addressed before merging.  @Xarthisius do you want to take another look?

**Comment by Xarthisius** [comment]
Just a side note: I was able to publish a Tale that I don't own. It only failed when it tried to update the Tale object with uri/doi:

```
Error updating Tale HTTP error 403: PUT http://girder:8080/api/v1/tale/5c9797e8c1cdad0001e2e025 Response text: {"message": "Write access denied for tale 5c9797e8c1cdad0001e2e025 (user 5c979c41c1cdad0001e2e035).", "type": "access"}

------------

[2019-03-24 15:28:13,164: ERROR/ForkPoolWorker-3] Task gwvolman.tasks.publish[27aac0b6-eedb-479f-a379-6382b81022ff] raised unexpected: ValueError('Error updating Tale HTTP error 403: PUT http://girder:8080/api/v1/tale/5c9797e8c1cdad0001e2e025\nResponse text: {"message": "Write access denied for tale 5c9797e8c1cdad0001e2e025 (user 5c979c41c1cdad0001e2e035).", "type": "access"}',)
Traceback (most recent call last):
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 244, in publish
    gc.put('tale/{}'.format(tale['_id']), json=tale)
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 519, in put
    json=json, jsonResp=jsonResp)
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 497, in sendRestRequest
    response=result)
girder_client.HttpError: HTTP error 403: PUT http://girder:8080/api/v1/tale/5c9797e8c1cdad0001e2e025
Response text: {"message": "Write access denied for tale 5c9797e8c1cdad0001e2e025 (user 5c979c41c1cdad0001e2e035).", "type": "access"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 410, in publish
    self.job_manager
  File "/gwvolman/gwvolman/lib/dataone/publish.py", line 247, in publish
    raise ValueError("Error updating Tale {}".format(str(e)))
ValueError: Error updating Tale HTTP error 403: PUT http://girder:8080/api/v1/tale/5c9797e8c1cdad0001e2e025
Response text: {"message": "Write access denied for tale 5c9797e8c1cdad0001e2e025 (user 5c979c41c1cdad0001e2e035).", "type": "access"}
```

**Comment by craig-willis** [comment]
Good catch, thank you.  I clearly dropped something from @ThomasThelen's original PR https://github.com/whole-tale/gwvolman/blob/76563fb922d6e01e005b6badb189a811c8f9a328/gwvolman/publish.py#L444

I feel like this check would be better placed in `girder_wholetale`, so I'll add it to https://github.com/whole-tale/girder_wholetale/pull/274 -- unless you say otherwise.

**Pull request merged**
